AllCops:
  NewCops: enable
  Exclude:
    - db/schema.rb
    - db/migrate/**/*
    - bin/*

Layout/HashAlignment:
  EnforcedColonStyle: table

Layout/LineLength:
  Max: 105

Lint/AmbiguousBlockAssociation:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Metrics/MethodLength:
  Max: 12

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
